input:
  fpkm: "test_data/ROR2_test/ROR2_fpkm_matrix.csv"
  metadata: "test_data/ROR2_test/Metadata.csv"

params:
  group_column: "shROR2_treatment"
  control_level: "no"
  treatment_level: "yes"

output:
  table: "results/diff_expr_results_ROR2.csv"
  plot: "results/volcano_plot_ROR2.png"